nombre = input("Ingrese nombre: ")
apellido = input("Ingrese apellido: ")
sección = input("Ingrese sección: ")
sede = input("Ingrese la sede: ")
print ("Nombre: " + nombre)
print ("Apellido: " + apellido)
print ("Sección: " + sección)
print ("Sede: " + sede)